language: python
os: linux
dist: bionic
jobs:
  include:
    - name: "docker-compose-build"
      if: branch NOT IN (master, dev) # already covered by docker-compose-test
      services: docker
      script: make build BUILD_OPTS="-q > /dev/null 2>&1" # quiet; otherwise travis job exceeds the maximum log length
    - name: "docker-compose-test"
      if: branch IN (master, dev)
      services: docker
      script: 
        - make test
      after_script:
        - ls -la ./data/ # mlflow artifact & tracking data
    - name: "Python 3.7"
      python: 3.7
      before_install:
        - pwd
        - ls -la
        - id
      install:
        - pip install -U pip
        - pip install tox-travis
        - pip install codecov
      script:
        - tox -e $TOX_PYTHON_ENV -e lint
      after_success:
        - codecov # submit coverage to https://codecov.io/gh/sertansenturk/makam_recognition_experiments/
      env: TOX_PYTHON_ENV=py37
before_install:
  - pip freeze
  - docker --version
  - pwd
  - ls -la
  - id
install:
  - 
before_script:
  -
script:
  - 
after_success:
  - 
after_script:
  - 